[SMTP]
sender_email = ABCXYZ@gmail.com
sender_password = xxxx xxxx xxxx xxxx

[RECIPIENT]
to_email = tujuan@oke.com
cc_email = tujuan2@oke.com

[CONTENT]
body = <b>Dear Mbak Afika,</b><br><br>Berikut terlampir data klaim "{nama_program}".<br>Mohon untuk dapat diproseskan.<br>Terima kasih.<br><br><b>Regards,</b><br><b>Saffiela</b>